SRC/models/user.schema.js
_tests_/signup.test.js

fixing automatic deployment issue caused by changing folder structure

Deployment issue

---

SRC/controllers/auth.controller.js
SRC/controllers/user.controller.js
SRC/middleware/authenticate.routes.js
SRC/models/user.schema.js
SRC/public/scripts/signup.js
SRC/routes/main.routes.js
SRC/views/Login.ejs
SRC/views/dummyDashboard.ejs
SRC/views/signup.ejs
index.js
package-lock.json
package.json

User sign in back end

---

SRC/controllers/auth.controller.js
SRC/controllers/user.controller.js
SRC/middleware/authenticate.routes.js
SRC/models/user.schema.js
SRC/public/scripts/signup.js
SRC/routes/main.routes.js
SRC/views/Login.ejs
SRC/views/dummyDashboard.ejs
SRC/views/dummystudentdashboard.ejs
SRC/views/signup.ejs
index.js
package-lock.json
package.json

Student is redirected to the student dashboard and the lecture to the lecture dashboard

File authentication

---

SRC/controllers/auth.controller.js
SRC/routes/main.routes.js
SRC/views/lecturerDashboard.ejs
SRC/views/studentDashboard.ejs

The user is able to see the student when logged in and can click the set appointment link to set appointments

Student dashboard

---

SRC/models/appointmentSchema.js
SRC/public/scripts/appointments.js
SRC/public/scripts/backendAppointment.js
SRC/routes/main.routes.js
SRC/views/scheduleAppointment.ejs
_tests_/appointment.test.js

- Has frontend and backend validation
- Save data to the database

Schedule appointment lecturer name

---

SRC/models/appointmentSchema.js
SRC/public/scripts/appointments.js
SRC/routes/main.routes.js
SRC/views/scheduleAppointment.ejs

Changes made:
- updated frontend for date input
- contains frontend validation for date and time
- saved date and time to the database
Note: 
- Will add backend validation and unit tests in the future

Schedule appointment date and time

---

SRC/routes/main.routes.js
SRC/views/Availability.ejs
SRC/views/lecturerDashboard.ejs

Availability times

---

index.js

The ports listen has now been update

Port Listen Fixed

---

SRC/views/scheduleAppointment.ejs

I have fixed the deployment bug causing the scheduling of appointments not to redirect to student page

fix deployed bug

---

SRC/public/scripts/Login.js
SRC/public/scripts/signup.js
SRC/public/styles/Login.css
SRC/public/styles/signup.css
SRC/views/Login.ejs
SRC/views/signup.ejs
_tests_/signup.test.js

Toggle password

---

SRC/controllers/auth.controller.js
SRC/routes/main.routes.js
SRC/views/lecturerDashboard.ejs

The student can make appointment with a certain lecture by specifying the lecture name, the appointment is also created on the lecture side and the lecture can see the created appointment

lecture views student appointments

---

SRC/controllers/auth.controller.js
SRC/routes/main.routes.js
SRC/views/lecturerDashboard.ejs
SRC/views/timeslots.ejs

The lecturer click on view timeslots to view the created time slots

Lecturer view created timeslots

---

_tests_/signup.test.js

Fixing npm tests to allow for deployement

Fixing test cases for deployment

---

SRC/models/appointmentSchema.js
SRC/public/scripts/appointments.js
SRC/routes/main.routes.js
SRC/views/lecturerDashboard.ejs
SRC/views/studentDashboard.ejs
index.js
package-lock.json
package.json

The student can cancel the appointment and see status change. The lecturer can also see that the meeting is cancelled since I have only dealt with one on one. Functionality for more than one student will be added.

Appointment status

---

SRC/models/appointmentSchema.js
SRC/public/scripts/appointments.js
SRC/routes/main.routes.js
SRC/views/lecturerCancelledAppointments.ejs
SRC/views/lecturerDashboard.ejs
SRC/views/studentCancelledAppointments.ejs
SRC/views/studentDashboard.ejs
index.js
package-lock.json
package.json

The user has a link leading to a table of all cancelled appointments

Cancelled appointments

---

SRC/controllers/auth.controller.js
SRC/models/appointmentSchema.js
SRC/public/scripts/appointments.js
SRC/public/scripts/hideflashmessage.js
SRC/public/styles/hideflashmessage.css
SRC/routes/main.routes.js
SRC/views/Login.ejs
SRC/views/lecturerCancelledAppointments.ejs
SRC/views/lecturerDashboard.ejs
SRC/views/messages.ejs
SRC/views/studentCancelledAppointments.ejs
SRC/views/studentDashboard.ejs
index.js
package-lock.json
package.json

The user sees messages according to the request output, whether it's a success or not and are redirected to a page according to the action results

User Authentication Flash messages

---

SRC/controllers/appointment.controller.js
SRC/models/appointmentSchema.js
SRC/public/scripts/appointments.js
SRC/routes/main.routes.js
SRC/views/scheduleAppointment.ejs
SRC/views/studentDashboard.ejs

The student can select an existing lecturer, after selecting the lecturer, all the timeslots created by the lecturer can be selected by the student to create an appointment. The date and time of the table is currently showing the id of the timeslot. this will be fixed on the branch dealing with the display of appointments.

Select timeslots

---

SRC/models/appointmentSchema.js
SRC/routes/main.routes.js
SRC/views/searchAppointment.ejs

Required fields

---

SRC/controllers/appointment.controller.js
SRC/routes/main.routes.js
SRC/views/searchAppointment.ejs

Flash errors search

---

SRC/views/searchAppointment.ejs
SRC/views/studentDashboard.ejs

Join Existing appointment

---

SRC/views/signup.ejs

Fixing the required fields in input

required inputs

---

SRC/routes/main.routes.js
SRC/views/update.ejs

Update times based on new schema
